### ISSUE TITLE
bower cache clean  command is failing

### ISSUE THREAD

**Issue by k-sudhan** [itemsapi/starter#22]
I was using the itemsapi starter code for past couple of months.  Also created a heroku deployment using the heroku button (everything worked like a charm).  But suddenly since Oct 2nd things started to fail locally on my box as well as on Heroku deployment. I am attaching the npm-debug.log file.

Can you please take a look at this issue.  Not sure why it started failing.

Thanks,

[npm-debug.log](https://github.com/itemsapi/starter/files/1364049/npm-debug.log)

**Comment by cigolpl** [comment]
Hey, it's surprising because nothing has been changed since that time. 
I got such such information in logs while testing on heroku:

`bower ECONFLICT Unable to find suitable version for jquery`. I think the solution is to add proper jquery version to bower because it seems bower has a conflict of version resolution problem. 

Also it would make sense maybe to migrate fully from bower to npm or yarn in some point in the future.

I could test it out when I find more time. In the meantime feel free to propose a change / improvement. Maybe you will find some solution

**Comment by cigolpl** [comment]
@k-sudhan happy to announce this commit https://github.com/itemsapi/starter/commit/e1655d01213b6b25e854f6e7d5a100a7d495583a has fixed this issue. 

Please use from now in this project `yarn` instead of `npm` as yarn had the easiest way for bower migration.

**Comment by k-sudhan** [comment]
@cigolpl 

Thanks for the fix.  Sorry couldn't respond back early as I was away for a while.

Thank you once again.
